name: Promote Charm

on:
  workflow_dispatch:
    inputs:
        origin-channel:
            type: choice
            description: 'Origin Channel'
            options:
            - latest/edge
            - latest/beta
            - latest/candidate
        destination-channel:
            type: choice
            description: 'Destination Channel'
            options:
            - latest/beta
            - latest/candidate
            - latest/stable
        base-channel:
            type: choice
            description: 'Base Channel to promote'
            options:
            - "20.04"
            - "22.04"
            - "24.04"

    secrets:
        CHARMHUB_TOKEN:
            required: true

jobs:
  promote:
    name: Promote Charm for base ${{ inputs.base-channel }}
    uses: canonical/operator-workflows/.github/workflows/promote_charm.yaml@main
    with:
      origin-channel: ${{ inputs.origin-channel }}
      destination-channel: ${{ inputs.destination-channel }}
      base-channel: ${{ inputs.base-channel }}
      base-name: ubuntu
      base-architecture: amd64
    secrets: inherit
