name: Publish Charm

on:
  push:
    branches:
      - main
    paths-ignore:
      - "bundle/**"
  workflow_dispatch:

run-name: Release charm by @${{ github.actor }}

jobs:
  upload-livepatch-operator-k8s:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@main
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: "latest/edge"
